# This file was generated by GoReleaser. DO NOT EDIT.
cask "nine-tails" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "610d626de2de61ab4fbaedf370636596b49ad38a08dc5f835cac67cba96f01d4"
      url "https://github.com/scottmeyer/nine-tails/releases/download/v#{version}/nine-tails_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b651fb62105de65070ea3e51ca978c3b3a8c2544b80e6d9f7f6a7dd77265aa4"
      url "https://github.com/scottmeyer/nine-tails/releases/download/v#{version}/nine-tails_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5abca8c7d93f038856921d56dbd1067ef096e29c06119ed25e88a6419d2b4f81"
      url "https://github.com/scottmeyer/nine-tails/releases/download/v#{version}/nine-tails_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9bba93506297c2d46290eb15f255378fc8776da93f6887f228a0fd581e56ea6b"
      url "https://github.com/scottmeyer/nine-tails/releases/download/v#{version}/nine-tails_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "nine-tails"
  desc "Persistent context sidecar for AI coding agents"
  homepage "https://github.com/scottmeyer/nine-tails"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nine-tails"

  generate_completions_from_executable "nine-tails", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
