# This file was generated by GoReleaser. DO NOT EDIT.
cask "nine-tails" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "83982135d104167f0c936305ae0b0e0ea278b57457b5952f0c1eb06b4fba6586"
      url "https://github.com/scottmeyer/nine-tails/releases/download/v#{version}/nine-tails_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d33af2cdcdde3572a1f656c0b0a5293039ac9e5af5f88e594120bcc3a332fbc2"
      url "https://github.com/scottmeyer/nine-tails/releases/download/v#{version}/nine-tails_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "20a04133778566fb380dfc4f06556f8618caf220deb97e58648ed04a8dcd5c20"
      url "https://github.com/scottmeyer/nine-tails/releases/download/v#{version}/nine-tails_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "254381b913fde98d3c4368df7049dd71269d97208826eb85f2c2906afce9f713"
      url "https://github.com/scottmeyer/nine-tails/releases/download/v#{version}/nine-tails_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "nine-tails"
  desc "Persistent context sidecar for AI coding agents"
  homepage "https://github.com/scottmeyer/nine-tails"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nine-tails"

  generate_completions_from_executable "nine-tails", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
